version: "3.3" 
services:
  database:
    container_name: database
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: firststep
    ports:
    - 3306
    volumes:
      - myvolume:/var/lib/mysql/
    networks:
      - net
  flask:
    container_name: flask-app-container
    depends_on:
      - database
    image: suahcho/app_img:1.7
    expose:
    - 5000
    networks:
      - net
  nginx:
    depends_on:
      - flask
    image: nginx
    volumes:
      - .\nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
    - "80:80"
    networks:
      - net

volumes:
  myvolume : {}

networks:
  net:
    driver: bridge
